# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsx < Formula
  desc "Helps setting aws cli credentials using aws sso"
  homepage "https://github.com/vahid-haghighat/awsx"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.5.0/awsx_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "81d56687c53a552c4c2ba38da22046e3c9d68f0cbea2d1e8c4faa0a0f1f11bca"

      def install
        bin.install "awsx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.5.0/awsx_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1b1972c6c6bd2b2ef569d321ad38af75e818db8e173d581793b176b8491c262c"

      def install
        bin.install "awsx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.5.0/awsx_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "48e9fa9655eb6124c71d9317dbce63128ee870cf650e0c31edf3672d62290de8"
      def install
        bin.install "awsx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.5.0/awsx_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1e840a0ad11174eec72c2406f3419467ff87e529980b7265540c9b808f2c81ac"
      def install
        bin.install "awsx"
      end
    end
  end

  test do
    system "#{bin}/awsx --version"
  end
end
