# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsx < Formula
  desc "Helps setting aws cli credentials using aws sso"
  homepage "https://github.com/vahid-haghighat/awsx"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.0/awsx_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5dee1c8f3b184dc62f2f2553ef8afbec22689c7bb81440e6a9491c6442ceb2e3"

      def install
        bin.install "awsx"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.0/awsx_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "42be1606ba234b5a44fe9a34e86001e30d7fceb93dea99ee395bff24e91be6fb"

      def install
        bin.install "awsx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.0/awsx_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "c45d5c5cc1f3156c7874d5a56297c5573d6c7d0fc56f774c94ff10ac318d7aeb"

        def install
          bin.install "awsx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.0/awsx_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "28b2868bd9ff0fd7eddac22f1540bdb3c694f86ee496a7bef34b4d96d10a7a36"

        def install
          bin.install "awsx"
        end
      end
    end
  end

  test do
    system "#{bin}/awsx --version"
  end
end
