# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsx < Formula
  desc "Helps setting aws cli credentials using aws sso"
  homepage "https://github.com/vahid-haghighat/awsx"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.1/awsx_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e347044705e1aceb61a33f5b42abfa5016cb594fbc0e2fa49101de41e730c056"

      def install
        bin.install "awsx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.1/awsx_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "712eb02d65c3c24fbb9c0990e7ac3479bd33125be2bdadd9a58f0a3214168516"

      def install
        bin.install "awsx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.1/awsx_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "542306a4bd6b7c08b62b0685eb26073773961a14059f9cfd9245203a8a3ee195"

        def install
          bin.install "awsx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/awsx/releases/download/v1.0.1/awsx_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "3a3a5772a842ec78ec04c70a921340eb3d3a4cda60c94155197b9af2ed7a48d0"

        def install
          bin.install "awsx"
        end
      end
    end
  end

  test do
    system "#{bin}/awsx --version"
  end
end
